# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chungloai',
            fields=[
                ('Chungloai_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Anh', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Linhkien',
            fields=[
                ('Linhkien_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Anh', models.FileField(null=True, upload_to='')),
                ('Chitiet', models.TextField()),
                ('Gia', models.FloatField()),
                ('Thoigian', models.DateTimeField(auto_now_add=True)),
                ('Chungloais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cuahang.Chungloai')),
            ],
        ),
    ]
