# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linhvuc',
            fields=[
                ('Linhvuc_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Anh', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
