# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trangchu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('Sanpham_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Anh', models.FileField(null=True, upload_to='')),
                ('Mieuta', models.TextField()),
                ('Filekem', models.FileField(null=True, upload_to='')),
                ('Caukien', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
