# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trangchu', '0003_auto_20171117_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='Linhvucs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trangchu.Linhvuc'),
        ),
    ]
