# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trangchu', '0004_sanpham_linhvucs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cacsanpham',
            fields=[
                ('sanpham_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Trangchu.Sanpham')),
            ],
            bases=('Trangchu.sanpham',),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='Anh',
            field=models.FileField(help_text='Anh cho linh kien', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='Filekem',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
